import { z } from 'zod';

const BloodGroupEnum = z.enum(['A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE']);
const CategoryEnum = z.enum(['GENERAL', 'OBC', 'SC', 'ST', 'EWS']);
const GuardianRelationEnum = z.enum(['FATHER', 'MOTHER', 'GUARDIAN', 'UNCLE', 'AUNT', 'GRANDFATHER', 'GRANDMOTHER', 'SIBLING', 'OTHER']);
const StudentStatusEnum = z.enum(['ACTIVE', 'INACTIVE', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'SUSPENDED']);
const AdmissionTypeEnum = z.enum(['REGULAR', 'TRANSFER', 'RE_ADMISSION']);
const GenderEnum = z.enum(['MALE', 'FEMALE', 'OTHER', 'Male', 'Female', 'Other'])
  .transform((v) => v.toUpperCase() as 'MALE' | 'FEMALE' | 'OTHER');

// Date of birth: required, must be a real date, and cannot be in the future.
const dateOfBirthSchema = z
  .string({ required_error: 'Date of birth is required' })
  .min(1, 'Date of birth is required')
  .refine((val) => !isNaN(new Date(val).getTime()), 'Date of birth is invalid')
  .refine((val) => new Date(val) <= new Date(), 'Date of birth cannot be in the future')
  .transform((val) => new Date(val));

// Roll number arrives as a string from multipart/form-data, so coerce to a number.
const rollNumberSchema = z.coerce
  .number({ required_error: 'Roll number is required', invalid_type_error: 'Roll number must be a number' })
  .int('Roll number must be a whole number')
  .positive('Roll number must be greater than 0');

const StudentSchema = z.object({
  // Admission Number is auto-generated by the server — never accepted from the client.
  grNo: z.string().optional(),
  rollNumber: rollNumberSchema,

  firstName: z.string().trim().min(1, 'First name is required'),
  middleName: z.string().trim().optional(),
  lastName: z.string().trim().min(1, 'Last name is required'),

  gender: GenderEnum,
  dateOfBirth: dateOfBirthSchema,
  bloodGroup: BloodGroupEnum,
  category: CategoryEnum,
  religion: z.string().trim().min(1, 'Religion is required'),
  caste: z.string().trim().optional(),
  nationality: z.string().trim().min(1, 'Nationality is required').default('Indian'),

  aadhaar: z.union([z.literal(''), z.string().regex(/^[0-9]{12}$/, 'Aadhaar must be 12 digits')]).optional()
    .transform((v) => (v === '' ? undefined : v)),
  passportNumber: z.union([z.literal(''), z.string().trim().min(1)]).optional()
    .transform((v) => (v === '' ? undefined : v)),
  mobile: z.union([z.literal(''), z.string().regex(/^[0-9]{10}$/, 'Student mobile number must be 10 digits')]).optional()
    .transform((v) => (v === '' ? undefined : v)),
  email: z.string().trim().email('Invalid email format'),

  alternateMobile: z.string().regex(/^[0-9]{10}$/, 'Alternate mobile must be 10 digits').optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  pincode: z.string().regex(/^[0-9]{6}$/, 'Pincode must be 6 digits').optional(),

  guardianName: z.string().trim().min(1, 'Guardian name is required'),
  guardianRelation: GuardianRelationEnum,
  guardianMobile: z.string().regex(/^[0-9]{10}$/, 'Guardian mobile must be 10 digits'),
  guardianEmail: z.string().email('Invalid email format').optional(),
  guardianAddress: z.string().optional(),
  guardianOccupation: z.string().optional(),

  classId: z.string().min(1, 'Class is required'),
  sectionId: z.string().min(1, 'Section is required'),

  admissionDate: z.string().transform((str) => new Date(str)).optional(),
  admissionType: AdmissionTypeEnum.optional(),
  status: StudentStatusEnum.optional(),

  previousSchool: z.string().optional(),
  heightCm: z.coerce.number().positive().optional(),
  weightKg: z.coerce.number().positive().optional(),
  medicalInfo: z.record(z.any()).optional(),
  transportDetails: z.record(z.any()).optional(),
  hostelDetails: z.record(z.any()).optional(),
});

export const CreateStudentSchema = StudentSchema;

export const UpdateStudentSchema = StudentSchema.partial();

export const GetStudentsQuerySchema = z.object({
  page: z.string().optional().transform(Number).default('1'),
  limit: z.string().optional().transform(Number).default('10'),
  search: z.string().optional(),
  classId: z.string().uuid().optional(),
  sectionId: z.string().uuid().optional(),
  status: StudentStatusEnum.optional(),
  sortBy: z.enum(['admissionNo', 'rollNumber', 'firstName', 'lastName', 'createdAt']).optional().default('createdAt'),
  sortOrder: z.enum(['asc', 'desc']).optional().default('desc'),
});